### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Peter Parker",
  "email": "pparker@example.com",
  "password": "Spiderman",
  "password_confirmation": "Spiderman"
}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "pparker@example.com",
  "password": "Spiderman"
}