### products index
GET http://localhost:3000/products.json
Content-Type: application/json

### products show
GET http://localhost:3000/products/3.json
Content-Type: application/json

###product create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "keychain",
  "price": 5,
  "image_url": "image.jpg",
  "description": "a buddy for your keys"
}

###product update
PATCH http://localhost:3000/products/10.json
Content-Type: application/json

{

 "description": "a fun buddy for your keys"
}

###product delete

DELETE http://localhost:3000/products/2
Content-Type: application/json
