### products index
GET http://localhost:3000/products.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDc5NzE5NDJ9.f1c4yiZCwfwqWrtvy1f6VR9iViSKQjznybQTqDQF5FE

### products show
GET http://localhost:3000/products/3.json
Content-Type: application/json

###product create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "test item 1",
  "price": "5",
  "image_url": "image.jpg",
  "description": "test description"
}

###product update
PATCH http://localhost:3000/products/3.json
Content-Type: application/json

{

 "image_url": "https://i.etsystatic.com/11988511/r/il/5457a2/2931932728/il_1588xN.2931932728_6qva.jpg"
}

###product delete

DELETE http://localhost:3000/products/2
Content-Type: application/json
