### products index
GET http://localhost:3000/products.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDc5NzE5NDJ9.f1c4yiZCwfwqWrtvy1f6VR9iViSKQjznybQTqDQF5FE

### products show
GET http://localhost:3000/products/3.json
Content-Type: application/json

###product create
POST http://localhost:3000/products.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDgwNjE4Njd9.Sv_FLOjLOVqMNiGGjprQBCZSWUbA0fjL1V-J5YZ4yIs

{
  "name": "Toothbrush",
  "price": "3",
  "description": "cleans your teeth",
  "supplier_id": "3"

}

###product update
PATCH http://localhost:3000/products/3.json
Content-Type: application/json

{

 "image_url": "https://i.etsystatic.com/11988511/r/il/5457a2/2931932728/il_1588xN.2931932728_6qva.jpg"
}

###product delete

DELETE http://localhost:3000/products/2
Content-Type: application/json

###orders create
POST http://localhost:3000/orders
Content-Type: application/json

{
  "user_id": "2",
  "product_id": "1",
  "quantity": "1",
  "subtotal": "999",
  "tax": "12",
  "total": "1011"
}

###orders show
GET http://localhost:3000/orders/1
Content-Type: application/json

###orders index

GET http://localhost:3000/orders
Content-Type: application/json